apiVersion: v1
kind: Deployment
metadata:
  name: my-cudos-app
spec:
  containers:
    - name: my-container
      image: your-dockerhub-username/my-cudos-app:latest
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
